In [4]:
import pandas as pd
df = pd.read_excel("../data/raw/zuwendungen_2025.xlsx")
df.head()

,INEZ-Nummer,Bescheiddatum,Bescheidart,Zuwendungsempfänger,Behörde,Dienststelle,AKZ,ZuwendungszeitraumVon,ZuwendungszeitraumBis,Zuwendungszweck,Förderungsart,Finanzierungsart,Finanzierungsform,Summe von Betriebskostenanteil,Summe von Investitionskostenanteil,Summe von Rückforderungen,Summe von Zuwendungssumme
0,ZUW-2025-03644,2025-12-30,Zuwendungsbescheid,"Haus 3, Stadtteilzentrum in Altona e.V.",Bezirksamt Altona,NaN,ZUW-2025-03644-InstiFö Haus 3,2026-01-01,2026-12-31,"Institutionelle Förderung der Sach-, Betriebs-...",Institutionelle Förderung,Festbetragsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,437540.90
1,ZUW-2025-02032,2025-12-30,Zuwendungsbescheid,PASSAGE gemeinnützige Gesellschaft für Arbeit ...,"Behörde für Wirtschaft, Arbeit und Innovation",IT-Ressourcen,"Z.601.15-1-2,2026",2026-01-01,2026-12-31,Optimierung der Beschäftigungsfähigkeit und Ar...,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,333358.62
2,ZUW-2025-00827,2025-12-30,Zuwendungsbescheid,HEnW KommunalEnergie GmbH,"Behörde für Umwelt, Klima, Energie und Agrarwi...",NaN,ZUW-2025-00827,2025-10-28,2026-10-31,Datenschutzwürdiger Zweck,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,245000.00
3,ZUW-2025-03850,2025-12-30,Zuwendungsbescheid,Stiftung Zukunftsrat Hamburg e.V.,"Behörde für Umwelt, Klima, Energie und Agrarwi...",NaN,ZUW-2025-03850,2026-01-01,2026-12-31,Förderung des laufenden Betriebs und der Aktiv...,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,57000.00
4,ZUW-2025-03985,2025-12-30,Zuwendungsbescheid,Initiative Schwarze Menschen in Deutschland (I...,Behörde für Kultur und Medien,NaN,ZUW-2025-03985,2025-12-19,2026-05-31,Ausstellung und Film - 30 Jahre BHM in Hamburg,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,24020.00

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76961 entries, 0 to 76960
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   INEZ-Nummer                         76961 non-null  str
 1   Bescheiddatum                       76961 non-null  datetime64[us]
 2   Bescheidart                         76961 non-null  str
 3   Zuwendungsempfänger                 76961 non-null  str
 4   Behörde                             76961 non-null  str
 5   Dienststelle                        72731 non-null  str
 6   AKZ                                 76954 non-null  str
 7   ZuwendungszeitraumVon               76961 non-null  datetime64[us]
 8   ZuwendungszeitraumBis               76961 non-null  datetime64[us]
 9   Zuwendungszweck                     76961 non-null  str
 10  Förderungsart                       76959 non-null  str
 11  Finanzierungsart                    76959 non-null  str
 12  Finanzierungsform                   76950 non-null  str
 13  Summe von Betriebskostenanteil      59421 non-null  float64
 14  Summe von Investitionskostenanteil  59421 non-null  float64
 15  Summe von Rückforderungen           59421 non-null  float64
 16  Summe von Zuwendungssumme           76961 non-null  float64
dtypes: datetime64[us](3), float64(4), str(10)
memory usage: 10.0 MB

In [6]:
empfaenger_summe = df.groupby("Zuwendungsempfänger")["Summe von Zuwendungssumme"].sum()
empfaenger_summe.sort_values(ascending=False).head(10)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                      8.667094e+09
Universitätsklinikum Hamburg-Eppendorf                                     6.393099e+09
Hamburg Port Authority AöR                                                 6.031203e+09
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung              3.486135e+09
Historische Museen Hamburg                                                 1.342463e+09
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                  1.271388e+09
Thalia Theater Gesellschaft mit beschränkter Haftung                       1.174527e+09
Hamburger Kunsthalle Stiftung öffentlichen Rechts                          9.637956e+08
HGV Hamburger Gesellschaft f. Vermögens- und Beteiligungsmanagement mbH    9.518300e+08
DB InfraGO Aktiengesellschaft                                              8.610095e+08
Name: Summe von Zuwendungssumme, dtype: float64

In [7]:
mask = df.loc[:, "Zuwendungsempfänger"] == "Hamburger Hochbahn Aktiengesellschaft"
df.loc[mask, ["Bescheiddatum", "Bescheidart", "ZuwendungszeitraumVon", "ZuwendungszeitraumBis", "Summe von Zuwendungssumme"]]

,Bescheiddatum,Bescheidart,ZuwendungszeitraumVon,ZuwendungszeitraumBis,Summe von Zuwendungssumme
350,2025-12-17,Änderungsbescheid,2022-06-01,2025-12-31,585590.00
1126,2025-12-03,Änderungsbescheid,2016-12-08,2019-12-31,1439926.70
1555,2025-11-24,Änderungsbescheid,2016-03-15,2020-12-31,18697758.18
1627,2025-11-20,Änderungsbescheid,2019-09-26,2031-06-30,9750000.00
1628,2025-11-20,Zuwendungsbescheid,2025-01-01,2025-12-31,5000000.00
...,...,...,...,...,...
71966,2016-06-21,Zuwendungsbescheid,2015-11-25,2020-12-31,15000000.00
72453,2016-05-04,Änderungsbescheid,2015-03-30,2017-12-31,22790000.00
72994,2016-03-15,Zuwendungsbescheid,2015-10-09,2017-12-31,2000000.00
75815,2015-08-31,Zuwendungsbescheid,2015-03-30,2017-12-31,22881000.00
76342,2015-06-04,Zuwendungsbescheid,2015-11-24,2016-12-31,800000.00

In [8]:
pd.options.display.float_format = "{:,.2f}".format
empfaenger_summe.sort_values(ascending=False).head(10)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                     8,667,094,000.14
Universitätsklinikum Hamburg-Eppendorf                                    6,393,098,562.94
Hamburg Port Authority AöR                                                6,031,202,874.22
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung             3,486,134,624.72
Historische Museen Hamburg                                                1,342,463,096.99
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                 1,271,387,760.87
Thalia Theater Gesellschaft mit beschränkter Haftung                      1,174,526,630.17
Hamburger Kunsthalle Stiftung öffentlichen Rechts                           963,795,578.57
HGV Hamburger Gesellschaft f. Vermögens- und Beteiligungsmanagement mbH     951,830,000.00
DB InfraGO Aktiengesellschaft                                               861,009,528.24
Name: Summe von Zuwendungssumme, dtype: float64

In [9]:
pd.crosstab(index=df.loc[:, "Bescheidart"], columns="Anzahl")

col_0                                   Anzahl
Bescheidart
Aufhebungs- und Rückforderungsbescheid    1750
Aufhebungsbescheid                         504
Empfängerwechsel                           340
Rückforderungsbescheid                    5024
Teilbescheid                              1022
Zuwendungsbescheid                       42594
Zuwendungsvertrag                          476
Änderungsbescheid                        25183
Änderungsvertrag                            68

In [10]:
df.groupby("INEZ-Nummer").size().sort_values(ascending=False).head(10)

INEZ-Nummer
SF-076044    24
SF-095261    20
SF-078604    19
SF-084667    18
SF-090687    17
SF-083773    16
SF-099625    16
SF-095513    15
SF-095512    15
SF-095517    15
dtype: int64

In [11]:
maske = df.loc[:, "INEZ-Nummer"] == "SF-076044"
df.loc[maske, ["Bescheiddatum", "Bescheidart", "Summe von Zuwendungssumme"]].sort_values("Bescheiddatum")

      Bescheiddatum         Bescheidart  Summe von Zuwendungssumme
69243    2016-12-20  Zuwendungsbescheid               3,715,185.72
63112    2017-12-07   Änderungsbescheid               3,715,185.72
56088    2018-11-27   Änderungsbescheid               4,316,523.05
50537    2019-07-19   Änderungsbescheid               4,316,523.05
48765    2019-11-05   Änderungsbescheid               4,316,523.05
46118    2020-01-29   Änderungsbescheid               4,316,523.05
45554    2020-02-25   Änderungsbescheid               4,528,823.05
45448    2020-02-27   Änderungsbescheid               4,528,823.05
44527    2020-04-16   Änderungsbescheid               5,148,823.05
43977    2020-05-15   Änderungsbescheid               5,152,103.99
43358    2020-06-19   Änderungsbescheid               5,262,224.37
41671    2020-09-22   Änderungsbescheid               5,262,224.37
40287    2020-11-30   Änderungsbescheid               6,904,613.32
39322    2020-12-15   Änderungsbescheid               6,904,613.32
37826    2021-02-05   Änderungsbescheid               6,977,685.45
29969    2021-12-22   Änderungsbescheid               8,863,457.50
29124    2022-02-07   Änderungsbescheid              11,080,285.69
29022    2022-02-10   Änderungsbescheid              11,067,132.61
27053    2022-05-13   Änderungsbescheid              11,158,048.84
21207    2023-02-07   Änderungsbescheid              11,221,916.69
20460    2023-03-16    Empfängerwechsel              11,221,916.69
20398    2023-03-21   Änderungsbescheid              11,221,916.69
17624    2023-08-16   Änderungsbescheid              12,263,235.56
3919     2025-06-19   Änderungsbescheid              12,275,472.82

In [12]:
maske_ruecknahme = df.loc[:, "Bescheidart"] == "Aufhebungs- und Rückforderungsbescheid"
df.loc[maske_ruecknahme, "INEZ-Nummer"].head(10)

674     SF-103532
774     SF-104531
1124    SF-096950
1428    SF-103317
1546    SF-101932
1593    SF-103065
1856    SF-096945
1861    SF-102028
1972    SF-103442
1974    SF-104188
Name: INEZ-Nummer, dtype: str

In [13]:
maske = df.loc[:, "INEZ-Nummer"] == "SF-103532"
df.loc[maske, ["Bescheiddatum", "Bescheidart", "Summe von Zuwendungssumme"]].sort_values("Bescheiddatum")

,Bescheiddatum,Bescheidart,Summe von Zuwendungssumme
19271,2023-05-16,Zuwendungsbescheid,"425,900.00"
18290,2023-07-10,Änderungsbescheid,"462,573.75"
674,2025-12-12,Aufhebungs- und Rückforderungsbescheid,"462,573.75"

In [14]:
maske = df.loc[:, "INEZ-Nummer"] == "SF-103532"
df.loc[maske, ["Bescheiddatum", "Bescheidart", "Summe von Zuwendungssumme", "Summe von Rückforderungen"]].sort_values("Bescheiddatum")

,Bescheiddatum,Bescheidart,Summe von Zuwendungssumme,Summe von Rückforderungen
19271,2023-05-16,Zuwendungsbescheid,"425,900.00",0.00
18290,2023-07-10,Änderungsbescheid,"462,573.75",0.00
674,2025-12-12,Aufhebungs- und Rückforderungsbescheid,"462,573.75","2,591.51"

In [15]:
vorgaenge = df.sort_values(["INEZ-Nummer", "Bescheiddatum"]).drop_duplicates(subset="INEZ-Nummer", keep="last")
len(vorgaenge), df.loc[:, "INEZ-Nummer"].nunique()

(42085, 42085)

In [16]:
maske_rueck = vorgaenge.loc[:, "Summe von Rückforderungen"] > 0
maske_rueck.sum()

np.int64(6670)

In [17]:
vorgaenge.loc[:, "Summe von Rückforderungen"].sum(), vorgaenge.loc[:, "Summe von Zuwendungssumme"].sum()

(np.float64(93442366.81400001), np.float64(21092046036.0018))

In [18]:
anteil = vorgaenge.loc[maske_rueck, "Summe von Rückforderungen"] / vorgaenge.loc[maske_rueck, "Summe von Zuwendungssumme"]
anteil.describe()

count   6,670.00
mean        0.15
std         0.22
min         0.00
25%         0.02
50%         0.06
75%         0.17
max         1.16
dtype: float64

In [19]:
vorgaenge = df.sort_values(["INEZ-Nummer", "Bescheiddatum"]).drop_duplicates(subset="INEZ-Nummer", keep="last").copy()

In [20]:
vorgaenge.loc[:, "netto"] = vorgaenge.loc[:, "Summe von Zuwendungssumme"] - vorgaenge.loc[:, "Summe von Rückforderungen"].fillna(0)
vorgaenge.loc[:, "netto"].sum()

np.float64(20998603669.1878)

In [21]:
vorgaenge.loc[:, "ZuwendungszeitraumVon"].dt.year.value_counts().sort_index()

ZuwendungszeitraumVon
2015    1733
2016    3473
2017    3903
2018    3635
2019    4230
2020    3929
2021    4169
2022    4032
2023    3992
2024    3726
2025    4044
2026    1218
2027       1
Name: count, dtype: int64

In [22]:
df.groupby("INEZ-Nummer")["Bescheiddatum"].min().dt.year.value_counts().sort_index()

Bescheiddatum
2015    2580
2016    3385
2017    4097
2018    3818
2019    4182
2020    3800
2021    4255
2022    4043
2023    4021
2024    3924
2025    3980
Name: count, dtype: int64

In [23]:
erstjahr = df.groupby("INEZ-Nummer")["Bescheiddatum"].min().dt.year
vorgaenge.loc[:, "erstjahr"] = vorgaenge.loc[:, "INEZ-Nummer"].map(erstjahr)
vorgaenge.groupby("erstjahr")["netto"].sum()

erstjahr
2015     439,407,726.32
2016   1,315,969,094.00
2017   1,144,285,701.54
2018   1,393,909,463.55
2019   2,050,470,910.05
2020   4,423,780,621.48
2021   1,850,995,545.78
2022   2,268,571,720.11
2023   1,845,963,283.89
2024   1,649,240,977.81
2025   2,616,008,624.65
Name: netto, dtype: float64

In [24]:
vorgaenge.loc[:, "erstjahr"].isna().sum(), vorgaenge.groupby("erstjahr")["netto"].sum().sum()

(np.int64(0), np.float64(20998603669.1878))

In [25]:
#C1 — auf 2025 einschränken:

maske_2025 = vorgaenge.loc[:, "erstjahr"] == 2025
jahr = vorgaenge.loc[maske_2025, :].copy()
len(jahr), jahr.loc[:, "netto"].sum()

(3980, np.float64(2616008624.65))

In [26]:
maske_vr = jahr.loc[:, "Zuwendungsempfänger"] == "Vereinsregister"
jahr.loc[maske_vr, ["Zuwendungszweck", "Behörde", "netto"]]

,Zuwendungszweck,Behörde,netto
6747,Familienteam Mümmelmannsberg - Frühe Hilfen an...,Bezirksamt Hamburg-Mitte,"255,576.71"
6836,Familienteam Rothenburgsort,Bezirksamt Hamburg-Mitte,"43,884.19"
6723,Projekt STADTRADELN 2025 und 2026,"Behörde für Umwelt, Klima, Energie und Agrarwi...","103,000.00"
5068,Förderung der Exzellenzstrategie des Bundes un...,"Behörde für Wissenschaft, Forschung, Gleichste...","5,500,290.66"
1445,Neuordnung des Mahnmals St. Nikolai,Bezirksamt Hamburg-Mitte,"3,500,000.00"

In [27]:
jahr.loc[maske_vr, "Zuwendungsempfänger"] = "Vereinsregister " + jahr.loc[maske_vr, "INEZ-Nummer"]

In [28]:
#C2 — pro Empfänger summieren:

empfaenger = jahr.groupby("Zuwendungsempfänger")["netto"].sum().sort_values(ascending=False)
empfaenger.head(10)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                           1,556,091,000.00
Hamburg Port Authority AöR                                        148,371,106.91
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung      82,076,008.00
Universitätsklinikum Hamburg-Eppendorf                             47,534,045.53
Stiftung Hamburger Öffentliche Bücherhallen                        37,590,946.00
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung          36,163,999.00
Thalia Theater Gesellschaft mit beschränkter Haftung               33,515,473.00
Deutsche Forschungsgemeinschaft e.V.                               29,242,800.00
Hamburger Sportbund e.V.                                           25,340,280.00
Historische Museen Hamburg                                         24,566,574.52
Name: netto, dtype: float64

In [29]:
len(empfaenger)

1974

In [30]:
anteil = empfaenger / empfaenger.sum() * 100
anteil.cumsum().head(20)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                         59.48
Hamburg Port Authority AöR                                                    65.16
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung                 68.29
Universitätsklinikum Hamburg-Eppendorf                                        70.11
Stiftung Hamburger Öffentliche Bücherhallen                                   71.55
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                     72.93
Thalia Theater Gesellschaft mit beschränkter Haftung                          74.21
Deutsche Forschungsgemeinschaft e.V.                                          75.33
Hamburger Sportbund e.V.                                                      76.30
Historische Museen Hamburg                                                    77.24
Museum für Kunst und Gewerbe Hamburg                                          78.09
Hamburger Kunsthalle Stiftung öffentlichen Rechts                             78.79
Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)                         79.35
Museum am Rothenbaum - Kulturen und Künste der Welt                           79.85
Hamburg Tourismus GmbH                                                        80.33
HVV Hamburger Verkehrsverbund Gesellschaft mbH                                80.79
Sprinkenhof GmbH                                                              81.25
Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung   81.69
Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH                      82.12
Jugendhilfe e.V.                                                              82.51
Name: netto, dtype: float64

In [31]:
(anteil.cumsum() < 50).sum() + 1

np.int64(1)

In [32]:
anteil.head(50)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                                                       59.48
Hamburg Port Authority AöR                                                                                   5.67
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung                                                3.14
Universitätsklinikum Hamburg-Eppendorf                                                                       1.82
Stiftung Hamburger Öffentliche Bücherhallen                                                                  1.44
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                                                    1.38
Thalia Theater Gesellschaft mit beschränkter Haftung                                                         1.28
Deutsche Forschungsgemeinschaft e.V.                                                                         1.12
Hamburger Sportbund e.V.                                                                                     0.97
Historische Museen Hamburg                                                                                   0.94
Museum für Kunst und Gewerbe Hamburg                                                                         0.85
Hamburger Kunsthalle Stiftung öffentlichen Rechts                                                            0.70
Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)                                                        0.57
Museum am Rothenbaum - Kulturen und Künste der Welt                                                          0.49
Hamburg Tourismus GmbH                                                                                       0.49
HVV Hamburger Verkehrsverbund Gesellschaft mbH                                                               0.46
Sprinkenhof GmbH                                                                                             0.46
Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung                                  0.45
Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH                                                     0.43
Jugendhilfe e.V.                                                                                             0.39
HHW Hamburger Hochbahn-Wache GmbH                                                                            0.37
SAGA Siedlungs-Aktiengesellschaft Hamburg                                                                    0.34
"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien    0.32
Studierendenwerk Hamburg Anstalt des öffentlichen Rechts                                                     0.29
Hamburger Symphoniker e.V.                                                                                   0.27
Deutsches Klimarechenzentrum GmbH                                                                            0.26
Deichtorhallen Hamburg GmbH                                                                                  0.25
zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                      0.25
NMS New Mobility Solutions Hamburg GmbH                                                                      0.25
HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH                                                     0.24
HamburgMusik gGmbH                                                                                           0.23
Hamburg Kreativ GmbH                                                                                         0.22
Handwerkskammer Hamburg                                                                                      0.21
Vereinsregister ZUW-2025-00367                                                                               0.21
Hamburg Marketing GmbH                                                                                       0.19
Basis & Woge e.V.                                                                                            0.19
Archäologisches Museum Hamburg und Stadtmuseum Harburg                                                       0.17
Verband Kinder- und Jugendarbeit Hamburg e.V.                                                                0.16
hamburger arbeit GmbH                                                                                        0.16
Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen                  0.15
Therapiehilfe gemeinnützige GmbH                                                                             0.15
Hamburger Fußball-Verband e.V.                                                                               0.14
Elbkinder Vereinigung Hamburger Kitas gGmbH                                                                  0.14
Der Kinderschutzbund Landesverband Hamburg e.V.                                                              0.14
STÄITSCH Theaterbetriebsgesellschaft mbH                                                                     0.14
Vereinsregister ZUW-2025-00986                                                                               0.13
Hamburg Innovation GmbH                                                                                      0.13
"Sprungbrett e.V."                                                                                           0.13
Gsm GmbH                                                                                                     0.13
Arbeiterwohlfahrt Landesverband Hamburg e.V.                                                                 0.12
Name: netto, dtype: float64

In [33]:
pd.options.display.max_rows = 60
anteil.head(50)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                                                       59.48
Hamburg Port Authority AöR                                                                                   5.67
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung                                                3.14
Universitätsklinikum Hamburg-Eppendorf                                                                       1.82
Stiftung Hamburger Öffentliche Bücherhallen                                                                  1.44
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                                                    1.38
Thalia Theater Gesellschaft mit beschränkter Haftung                                                         1.28
Deutsche Forschungsgemeinschaft e.V.                                                                         1.12
Hamburger Sportbund e.V.                                                                                     0.97
Historische Museen Hamburg                                                                                   0.94
Museum für Kunst und Gewerbe Hamburg                                                                         0.85
Hamburger Kunsthalle Stiftung öffentlichen Rechts                                                            0.70
Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)                                                        0.57
Museum am Rothenbaum - Kulturen und Künste der Welt                                                          0.49
Hamburg Tourismus GmbH                                                                                       0.49
HVV Hamburger Verkehrsverbund Gesellschaft mbH                                                               0.46
Sprinkenhof GmbH                                                                                             0.46
Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung                                  0.45
Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH                                                     0.43
Jugendhilfe e.V.                                                                                             0.39
HHW Hamburger Hochbahn-Wache GmbH                                                                            0.37
SAGA Siedlungs-Aktiengesellschaft Hamburg                                                                    0.34
"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien    0.32
Studierendenwerk Hamburg Anstalt des öffentlichen Rechts                                                     0.29
Hamburger Symphoniker e.V.                                                                                   0.27
Deutsches Klimarechenzentrum GmbH                                                                            0.26
Deichtorhallen Hamburg GmbH                                                                                  0.25
zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                      0.25
NMS New Mobility Solutions Hamburg GmbH                                                                      0.25
HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH                                                     0.24
HamburgMusik gGmbH                                                                                           0.23
Hamburg Kreativ GmbH                                                                                         0.22
Handwerkskammer Hamburg                                                                                      0.21
Vereinsregister ZUW-2025-00367                                                                               0.21
Hamburg Marketing GmbH                                                                                       0.19
Basis & Woge e.V.                                                                                            0.19
Archäologisches Museum Hamburg und Stadtmuseum Harburg                                                       0.17
Verband Kinder- und Jugendarbeit Hamburg e.V.                                                                0.16
hamburger arbeit GmbH                                                                                        0.16
Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen                  0.15
Therapiehilfe gemeinnützige GmbH                                                                             0.15
Hamburger Fußball-Verband e.V.                                                                               0.14
Elbkinder Vereinigung Hamburger Kitas gGmbH                                                                  0.14
Der Kinderschutzbund Landesverband Hamburg e.V.                                                              0.14
STÄITSCH Theaterbetriebsgesellschaft mbH                                                                     0.14
Vereinsregister ZUW-2025-00986                                                                               0.13
Hamburg Innovation GmbH                                                                                      0.13
"Sprungbrett e.V."                                                                                           0.13
Gsm GmbH                                                                                                     0.13
Arbeiterwohlfahrt Landesverband Hamburg e.V.                                                                 0.12
Name: netto, dtype: float64

In [34]:

anteil.iloc[20:50]

Zuwendungsempfänger
HHW Hamburger Hochbahn-Wache GmbH                                                                           0.37
SAGA Siedlungs-Aktiengesellschaft Hamburg                                                                   0.34
"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien   0.32
Studierendenwerk Hamburg Anstalt des öffentlichen Rechts                                                    0.29
Hamburger Symphoniker e.V.                                                                                  0.27
Deutsches Klimarechenzentrum GmbH                                                                           0.26
Deichtorhallen Hamburg GmbH                                                                                 0.25
zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                     0.25
NMS New Mobility Solutions Hamburg GmbH                                                                     0.25
HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH                                                    0.24
HamburgMusik gGmbH                                                                                          0.23
Hamburg Kreativ GmbH                                                                                        0.22
Handwerkskammer Hamburg                                                                                     0.21
Vereinsregister ZUW-2025-00367                                                                              0.21
Hamburg Marketing GmbH                                                                                      0.19
Basis & Woge e.V.                                                                                           0.19
Archäologisches Museum Hamburg und Stadtmuseum Harburg                                                      0.17
Verband Kinder- und Jugendarbeit Hamburg e.V.                                                               0.16
hamburger arbeit GmbH                                                                                       0.16
Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen                 0.15
Therapiehilfe gemeinnützige GmbH                                                                            0.15
Hamburger Fußball-Verband e.V.                                                                              0.14
Elbkinder Vereinigung Hamburger Kitas gGmbH                                                                 0.14
Der Kinderschutzbund Landesverband Hamburg e.V.                                                             0.14
STÄITSCH Theaterbetriebsgesellschaft mbH                                                                    0.14
Vereinsregister ZUW-2025-00986                                                                              0.13
Hamburg Innovation GmbH                                                                                     0.13
"Sprungbrett e.V."                                                                                          0.13
Gsm GmbH                                                                                                    0.13
Arbeiterwohlfahrt Landesverband Hamburg e.V.                                                                0.12
Name: netto, dtype: float64

In [35]:
anteil.sum()

np.float64(100.0)

In [36]:
anteil.head(50)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                                                       59.48
Hamburg Port Authority AöR                                                                                   5.67
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung                                                3.14
Universitätsklinikum Hamburg-Eppendorf                                                                       1.82
Stiftung Hamburger Öffentliche Bücherhallen                                                                  1.44
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                                                    1.38
Thalia Theater Gesellschaft mit beschränkter Haftung                                                         1.28
Deutsche Forschungsgemeinschaft e.V.                                                                         1.12
Hamburger Sportbund e.V.                                                                                     0.97
Historische Museen Hamburg                                                                                   0.94
Museum für Kunst und Gewerbe Hamburg                                                                         0.85
Hamburger Kunsthalle Stiftung öffentlichen Rechts                                                            0.70
Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)                                                        0.57
Museum am Rothenbaum - Kulturen und Künste der Welt                                                          0.49
Hamburg Tourismus GmbH                                                                                       0.49
HVV Hamburger Verkehrsverbund Gesellschaft mbH                                                               0.46
Sprinkenhof GmbH                                                                                             0.46
Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung                                  0.45
Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH                                                     0.43
Jugendhilfe e.V.                                                                                             0.39
HHW Hamburger Hochbahn-Wache GmbH                                                                            0.37
SAGA Siedlungs-Aktiengesellschaft Hamburg                                                                    0.34
"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien    0.32
Studierendenwerk Hamburg Anstalt des öffentlichen Rechts                                                     0.29
Hamburger Symphoniker e.V.                                                                                   0.27
Deutsches Klimarechenzentrum GmbH                                                                            0.26
Deichtorhallen Hamburg GmbH                                                                                  0.25
zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                      0.25
NMS New Mobility Solutions Hamburg GmbH                                                                      0.25
HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH                                                     0.24
HamburgMusik gGmbH                                                                                           0.23
Hamburg Kreativ GmbH                                                                                         0.22
Handwerkskammer Hamburg                                                                                      0.21
Vereinsregister ZUW-2025-00367                                                                               0.21
Hamburg Marketing GmbH                                                                                       0.19
Basis & Woge e.V.                                                                                            0.19
Archäologisches Museum Hamburg und Stadtmuseum Harburg                                                       0.17
Verband Kinder- und Jugendarbeit Hamburg e.V.                                                                0.16
hamburger arbeit GmbH                                                                                        0.16
Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen                  0.15
Therapiehilfe gemeinnützige GmbH                                                                             0.15
Hamburger Fußball-Verband e.V.                                                                               0.14
Elbkinder Vereinigung Hamburger Kitas gGmbH                                                                  0.14
Der Kinderschutzbund Landesverband Hamburg e.V.                                                              0.14
STÄITSCH Theaterbetriebsgesellschaft mbH                                                                     0.14
Vereinsregister ZUW-2025-00986                                                                               0.13
Hamburg Innovation GmbH                                                                                      0.13
"Sprungbrett e.V."                                                                                           0.13
Gsm GmbH                                                                                                     0.13
Arbeiterwohlfahrt Landesverband Hamburg e.V.                                                                 0.12
Name: netto, dtype: float64

In [37]:
anteil.head(50)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                                                       59.48
Hamburg Port Authority AöR                                                                                   5.67
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung                                                3.14
Universitätsklinikum Hamburg-Eppendorf                                                                       1.82
Stiftung Hamburger Öffentliche Bücherhallen                                                                  1.44
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                                                    1.38
Thalia Theater Gesellschaft mit beschränkter Haftung                                                         1.28
Deutsche Forschungsgemeinschaft e.V.                                                                         1.12
Hamburger Sportbund e.V.                                                                                     0.97
Historische Museen Hamburg                                                                                   0.94
Museum für Kunst und Gewerbe Hamburg                                                                         0.85
Hamburger Kunsthalle Stiftung öffentlichen Rechts                                                            0.70
Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)                                                        0.57
Museum am Rothenbaum - Kulturen und Künste der Welt                                                          0.49
Hamburg Tourismus GmbH                                                                                       0.49
HVV Hamburger Verkehrsverbund Gesellschaft mbH                                                               0.46
Sprinkenhof GmbH                                                                                             0.46
Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung                                  0.45
Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH                                                     0.43
Jugendhilfe e.V.                                                                                             0.39
HHW Hamburger Hochbahn-Wache GmbH                                                                            0.37
SAGA Siedlungs-Aktiengesellschaft Hamburg                                                                    0.34
"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien    0.32
Studierendenwerk Hamburg Anstalt des öffentlichen Rechts                                                     0.29
Hamburger Symphoniker e.V.                                                                                   0.27
Deutsches Klimarechenzentrum GmbH                                                                            0.26
Deichtorhallen Hamburg GmbH                                                                                  0.25
zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                      0.25
NMS New Mobility Solutions Hamburg GmbH                                                                      0.25
HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH                                                     0.24
HamburgMusik gGmbH                                                                                           0.23
Hamburg Kreativ GmbH                                                                                         0.22
Handwerkskammer Hamburg                                                                                      0.21
Vereinsregister ZUW-2025-00367                                                                               0.21
Hamburg Marketing GmbH                                                                                       0.19
Basis & Woge e.V.                                                                                            0.19
Archäologisches Museum Hamburg und Stadtmuseum Harburg                                                       0.17
Verband Kinder- und Jugendarbeit Hamburg e.V.                                                                0.16
hamburger arbeit GmbH                                                                                        0.16
Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen                  0.15
Therapiehilfe gemeinnützige GmbH                                                                             0.15
Hamburger Fußball-Verband e.V.                                                                               0.14
Elbkinder Vereinigung Hamburger Kitas gGmbH                                                                  0.14
Der Kinderschutzbund Landesverband Hamburg e.V.                                                              0.14
STÄITSCH Theaterbetriebsgesellschaft mbH                                                                     0.14
Vereinsregister ZUW-2025-00986                                                                               0.13
Hamburg Innovation GmbH                                                                                      0.13
"Sprungbrett e.V."                                                                                           0.13
Gsm GmbH                                                                                                     0.13
Arbeiterwohlfahrt Landesverband Hamburg e.V.                                                                 0.12
Name: netto, dtype: float64

In [38]:
maske_g = jahr.loc[:, "Zuwendungsempfänger"] == "Gsm GmbH"
jahr.loc[maske_g, ["Zuwendungszweck", "Behörde", "netto", "ZuwendungszeitraumVon", "ZuwendungszeitraumBis"]]

,Zuwendungszweck,Behörde,netto,ZuwendungszeitraumVon,ZuwendungszeitraumBis
6569,Come in & Catch up,"Behörde für Wirtschaft, Arbeit und Innovation","3,389,114.62",2025-01-01,2026-12-31

In [39]:
pd.options.display.max_colwidth = 300
jahr.loc[maske_g, ["Zuwendungszweck", "AKZ", "Behörde"]]

,Zuwendungszweck,AKZ,Behörde
6569,Come in & Catch up,"Z.601.11-9-2,2025","Behörde für Wirtschaft, Arbeit und Innovation"

In [40]:
maske_akz = df.loc[:, "AKZ"] == "Z.601.11-9-2,2025"
maske_akz.sum(), df.loc[maske_akz, "INEZ-Nummer"].nunique()

(np.int64(1), 1)

In [41]:
df.loc[:, "AKZ"].nunique(), df.loc[:, "INEZ-Nummer"].nunique()

(41044, 42085)

In [42]:
traeger = {
    'Hamburger Hochbahn Aktiengesellschaft': 'staedtisch',
    'Hamburg Port Authority AöR': 'staedtisch',
    'Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung': 'staedtisch',
    'Universitätsklinikum Hamburg-Eppendorf': 'staedtisch',
    'Stiftung Hamburger Öffentliche Bücherhallen': 'nicht_staedtisch',
    'Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung': 'staedtisch',
    'Thalia Theater Gesellschaft mit beschränkter Haftung': 'staedtisch',
    'Deutsche Forschungsgemeinschaft e.V.': 'nicht_staedtisch',
    'Hamburger Sportbund e.V.': 'nicht_staedtisch',
    'Historische Museen Hamburg': 'staedtisch',
    'Museum für Kunst und Gewerbe Hamburg': 'staedtisch',
    'Hamburger Kunsthalle Stiftung öffentlichen Rechts': 'staedtisch',
    'Filmförderung Hamburg/Schleswig-Holstein GmbH (FFHSH)': 'gemischt_oeffentlich',
    'Museum am Rothenbaum - Kulturen und Künste der Welt': 'staedtisch',
    'Hamburg Tourismus GmbH': 'gemischt_oeffentlich',
    'HVV Hamburger Verkehrsverbund Gesellschaft mbH': 'staedtisch',
    'Sprinkenhof GmbH': 'staedtisch',
    'Kampnagel Internationale Kulturfabrik Gesellschaft mit beschränkter Haftung': 'staedtisch',
    'Elbphilharmonie und Laeiszhalle Betriebsgesellschaft mbH': 'staedtisch',
    'Jugendhilfe e.V.': 'nicht_staedtisch',
    'HHW Hamburger Hochbahn-Wache GmbH': 'staedtisch',
    'SAGA Siedlungs-Aktiengesellschaft Hamburg': 'staedtisch',
    '"German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien': 'nicht_staedtisch',
    'Studierendenwerk Hamburg Anstalt des öffentlichen Rechts': 'staedtisch',
    'Hamburger Symphoniker e.V.': 'nicht_staedtisch',
    'Deutsches Klimarechenzentrum GmbH': 'nicht_staedtisch',
    'Deichtorhallen Hamburg GmbH': 'staedtisch',
    'zwei P PLAN:PERSONAL gemeinnützige GmbH': 'nicht_staedtisch',
    'NMS New Mobility Solutions Hamburg GmbH': 'staedtisch',
    'HIW Hamburg Invest Wirtschaftsförderungsgesellschaft mbH': 'gemischt_oeffentlich',
    'HamburgMusik gGmbH': 'staedtisch',
    'Hamburg Kreativ GmbH': 'staedtisch',
    'Handwerkskammer Hamburg': 'nicht_staedtisch',
    'Vereinsregister ZUW-2025-00367': 'nicht_staedtisch',
    'Hamburg Marketing GmbH': 'staedtisch',
    'Basis & Woge e.V.': 'nicht_staedtisch',
    'Archäologisches Museum Hamburg und Stadtmuseum Harburg': 'staedtisch',
    'Verband Kinder- und Jugendarbeit Hamburg e.V.': 'nicht_staedtisch',
    'hamburger arbeit GmbH': 'staedtisch',
    'Stiftung Hamburger Gedenkstätten und Lernorte zur Erinnerung an die Opfer der NS-Verbrechen': 'staedtisch',
    'Therapiehilfe gemeinnützige GmbH': 'nicht_staedtisch',
    'Hamburger Fußball-Verband e.V.': 'nicht_staedtisch',
    'Elbkinder Vereinigung Hamburger Kitas gGmbH': 'staedtisch',
    'Der Kinderschutzbund Landesverband Hamburg e.V.': 'nicht_staedtisch',
    'STÄITSCH Theaterbetriebsgesellschaft mbH': 'nicht_staedtisch',
    'Vereinsregister ZUW-2025-00986': 'nicht_staedtisch',
    'Hamburg Innovation GmbH': 'nicht_staedtisch',
    '"Sprungbrett e.V."': 'nicht_staedtisch',
    'Gsm GmbH': 'nicht_staedtisch',
    'Arbeiterwohlfahrt Landesverband Hamburg e.V.': 'nicht_staedtisch',
}
len(traeger)

50

In [43]:
kategorie = empfaenger.index.map(traeger).fillna('nicht_staedtisch')
nach_kategorie = empfaenger.groupby(kategorie).sum()
nach_kategorie / nach_kategorie.sum() * 100

Zuwendungsempfänger
gemischt_oeffentlich    1.29
nicht_staedtisch       18.40
staedtisch             80.31
Name: netto, dtype: float64

In [44]:
nicht_staedtisch = empfaenger[kategorie == 'nicht_staedtisch']
anteil_ns = (nicht_staedtisch / nicht_staedtisch.sum() * 100).sort_values(ascending=False)
len(nicht_staedtisch), nicht_staedtisch.sum(), (anteil_ns.cumsum() < 50).sum() + 1

(1945, np.float64(481263067.91999996), np.int64(45))

In [45]:

anteil_ns.head(20), anteil_ns.head(20).sum()

(Zuwendungsempfänger
 Stiftung Hamburger Öffentliche Bücherhallen                                                                 7.81
 Deutsche Forschungsgemeinschaft e.V.                                                                        6.08
 Hamburger Sportbund e.V.                                                                                    5.27
 Jugendhilfe e.V.                                                                                            2.10
 "German Institute for Global and Area Studies" (GIGA), Leibniz-Institut für Globale und Regionale Studien   1.72
 Hamburger Symphoniker e.V.                                                                                  1.45
 Deutsches Klimarechenzentrum GmbH                                                                           1.40
 zwei P PLAN:PERSONAL gemeinnützige GmbH                                                                     1.35
 Handwerkskammer Hamburg                                                                                     1.15
 Vereinsregister ZUW-2025-00367                                                                              1.14
 Basis & Woge e.V.                                                                                           1.04
 Verband Kinder- und Jugendarbeit Hamburg e.V.                                                               0.88
 Therapiehilfe gemeinnützige GmbH                                                                            0.83
 Hamburger Fußball-Verband e.V.                                                                              0.78
 Der Kinderschutzbund Landesverband Hamburg e.V.                                                             0.75
 STÄITSCH Theaterbetriebsgesellschaft mbH                                                                    0.75
 Vereinsregister ZUW-2025-00986                                                                              0.73
 Hamburg Innovation GmbH                                                                                     0.72
 "Sprungbrett e.V."                                                                                          0.71
 Gsm GmbH                                                                                                    0.70
 Name: netto, dtype: float64,
 np.float64(37.359535348739385))

## Befund: nicht-städtische Empfänger

Die Top-50-Empfänger wurden gegen den Beteiligungsbericht der FHH geprüft (städtisch / gemischt-öffentlich / nicht-städtisch; unklare Fälle vorsichtshalber als nicht-städtisch gewertet).

| Gruppe | Anteil an 2,62 Mrd € |
|---|---|
| Städtisch | 80,3 % |
| Gemischt-öffentlich | 1,3 % |
| Nicht-städtisch | 18,4 % (481 Mio €) |

Unter den 1.945 nicht-städtischen Empfängern ist das Geld deutlich breiter gestreut als im Gesamtbild: Die Top 20 vereinen 37,4 % (statt 82,5 % gesamt), und 45 Empfänger brauchen für die Hälfte der Summe – nicht eine einzelne AG.